import {
  ActivityLog,
  InternalTask,
  PaymentFollowUp,
  PriorityEmail,
  StatCardData,
} from "@/types/domain";

export const dashboardStats: StatCardData[] = [
  {
    id: "payments-late",
    label: "Reglements en retard",
    value: 8,
    trend: "+2 cette semaine",
    priority: "urgente",
  },
  {
    id: "emails-pending",
    label: "Emails non traites",
    value: 17,
    trend: "-4 depuis hier",
    priority: "normale",
  },
  {
    id: "tasks-running",
    label: "Taches en cours",
    value: 11,
    trend: "3 a traiter aujourd'hui",
    priority: "normale",
  },
  {
    id: "appointments-today",
    label: "Rendez-vous aujourd'hui",
    value: 23,
    trend: "Journee chargee",
    priority: "faible",
  },
];

export const paymentFollowUps: PaymentFollowUp[] = [
  {
    id: "pay-001",
    patientId: "pat-001",
    patientName: "Mila Laurent",
    amountDue: 340,
    dueDate: "2026-05-03",
    daysLate: 8,
    status: "En retard",
    comment: null,
    relanceCount: 0,
    lastRelanceAt: null,
  },
  {
    id: "pay-002",
    patientId: "pat-002",
    patientName: "Noah Girard",
    amountDue: 120,
    dueDate: "2026-05-05",
    daysLate: 6,
    status: "Relance envoyee",
    comment: null,
    relanceCount: 1,
    lastRelanceAt: "2026-05-10T14:00:00.000Z",
  },
  {
    id: "pay-003",
    patientId: "pat-003",
    patientName: "Lina Caron",
    amountDue: 540,
    dueDate: "2026-05-01",
    daysLate: 10,
    status: "Partiel",
    comment: null,
    relanceCount: 0,
    lastRelanceAt: null,
  },
  {
    id: "pay-004",
    patientId: "pat-004",
    patientName: "Ethan Bernard",
    amountDue: 220,
    dueDate: "2026-05-07",
    daysLate: 4,
    status: "En retard",
    comment: null,
    relanceCount: 0,
    lastRelanceAt: null,
  },
];

export const priorityEmails: PriorityEmail[] = [
  {
    id: "mail-001",
    from: "m.parent@example.com",
    subject: "Question sur devis de contention",
    receivedDate: "11/05/2026",
    receivedAt: "08:42",
    category: "Urgent",
    status: "En cours",
    comment: null,
    patientId: "pat-001",
    patientName: "Mila Laurent",
    assigneeId: "user-001",
    assignee: "Sonia Martin",
  },
  {
    id: "mail-002",
    from: "ecole-centrale@example.com",
    subject: "Attestation de suivi pour eleve",
    receivedDate: "11/05/2026",
    receivedAt: "09:15",
    category: "Administratif",
    status: "A traiter",
    comment: null,
    patientId: null,
    patientName: null,
    assigneeId: null,
    assignee: "Non assignee",
  },
  {
    id: "mail-003",
    from: "drlambert@example.com",
    subject: "Coordination cas pedodontie",
    receivedDate: "10/05/2026",
    receivedAt: "10:08",
    category: "Suivi clinique",
    status: "Traite",
    comment: "Transmis au praticien.",
    patientId: "pat-003",
    patientName: "Lina Caron",
    assigneeId: null,
    assignee: "Non assignee",
  },
];

export const internalTasks: InternalTask[] = [
  {
    id: "task-001",
    title: "Relancer dossier impaye - Famille Laurent",
    comment: "Verifier avec la famille",
    assigneeId: "user-001",
    assignee: "Sonia",
    patientId: "patient-001",
    patientName: "Mila Laurent",
    dueDate: "2026-05-11",
    priority: "urgente",
    status: "En cours",
  },
  {
    id: "task-002",
    title: "Verifier consentements numeriques",
    comment: null,
    assigneeId: "user-002",
    assignee: "Yanis",
    patientId: "patient-002",
    patientName: "Noah Girard",
    dueDate: "2026-05-12",
    priority: "normale",
    status: "A faire",
  },
  {
    id: "task-003",
    title: "Mettre a jour planning fauteuil 2",
    comment: null,
    assigneeId: "user-003",
    assignee: "Nora",
    patientId: null,
    patientName: null,
    dueDate: "2026-05-11",
    priority: "faible",
    status: "A faire",
  },
];

export const activityLogs: ActivityLog[] = [
  {
    id: "act-001",
    message: "Relance de reglement envoyee a Mila Laurent",
    actor: "Sonia",
    createdAt: "Il y a 12 min",
  },
  {
    id: "act-002",
    message: "Email prioritaire classe dans Suivi clinique",
    actor: "Yanis",
    createdAt: "Il y a 24 min",
  },
  {
    id: "act-003",
    message: "Nouvelle tache interne creee: verification dossiers",
    actor: "Nora",
    createdAt: "Il y a 49 min",
  },
];
